# Generated by Django. Add the Section model for subject-section relation.
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(choices=[(0,'Artificial Intelliegnence and Machine Learninig'),(1,'Artificial Intelliegnence and Data Science'),(2,'A'),(3,'B'),(4,'C')], unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.Department')),
            ],
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='Select up to 3 sections for this subject.', related_name='semester_subjects', to='core.Section'),
        ),
    ]
