# Generated by Django 5.1 on 2025-08-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_spotfeedback_qr_code_spotfeedback_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BONAFIDE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('date', models.DateField(verbose_name='Date')),
                ('proof', models.FileField(blank=True, upload_to='bonafide/proof')),
                ('certificate', models.FileField(blank=True, upload_to='bonafide/proof/certificate')),
                ('Astatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('Mstatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('Hstatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_student', to='core.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
