# Generated by Django 5.2.5 on 2025-08-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_bonafide'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonafide',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
    ]
