# Generated by Django 5.2.5 on 2025-08-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_bonafide_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AddField(
            model_name='student',
            name='ahod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='AHOD', to='core.staff'),
        ),
        migrations.CreateModel(
            name='AHOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_feedback', models.BooleanField(default=False)),
                ('get_spot_feedback', models.BooleanField(default=False)),
                ('department', models.PositiveIntegerField(choices=[(0, 'B-Tech Artificial Intelliegnence'), (1, 'BE Computer Science and Engineering'), (3, 'BE Electrical and Communication Engineering'), (2, 'None')], default=2, null=True)),
                ('assign_feedback', models.ManyToManyField(blank=True, related_name='ahod_assign_feed', to='core.staff')),
                ('spot_feedback', models.ManyToManyField(blank=True, to='core.spotfeedback')),
                ('staffs', models.ManyToManyField(blank=True, related_name='ahod_my_staffs', to='core.staff')),
                ('students', models.ManyToManyField(blank=True, related_name='ahod_students', to='core.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
