# Generated by Django 5.2.5 on 2025-08-21 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_student_options_student_ahod_ahod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='student',
            name='a_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='A_Advisor', to='core.staff'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ahod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='AHOD', to='core.ahod'),
        ),
    ]
