# Generated by Django 5.0.6 on 2025-08-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_bonafide_ahodstatus_gatepass_ahodstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonafide',
            name='AHODstatus',
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='AHODstatus',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='AHODstatus',
        ),
        migrations.RemoveField(
            model_name='od',
            name='AHODstatus',
        ),
        migrations.AddField(
            model_name='staff',
            name='position2',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Head of the Department'), (1, 'Assistant Head of the Department'), (3, 'Lecturer')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='position3',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Head of the Department'), (1, 'Assistant Head of the Department'), (3, 'Lecturer')], default=0, null=True),
        ),
    ]
