# Generated by Django 5.2.5 on 2025-08-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_notification_user_notification_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='role',
            field=models.CharField(blank=True, choices=[('mentor', 'Mentor'), ('advisor', 'Advisor'), ('hod', 'HOD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
