# Generated by Django 5.0.6 on 2025-08-25 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_notification_role_alter_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonafide',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bonafide',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='bonafide',
            name='time',
        ),
        migrations.AddField(
            model_name='bonafide',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bonafide',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bonafide',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonafide_student', to='core.student'),
        ),
    ]
