# Generated by Django 5.2.5 on 2025-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_bonafide_date_remove_bonafide_sub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonafide',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonafide',
            name='sub',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
