# Generated by Django 5.0.6 on 2025-08-26 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_bonafide_date_bonafide_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('my_timetable_data', models.JSONField(default=dict)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='core.staff')),
            ],
        ),
    ]
