# Generated by Django 5.2.5 on 2025-08-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_bonafide_ahstatus_gatepass_ahstatus_leave_ahstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.PositiveIntegerField(blank=True, help_text='Enter start year, e.g., 2023', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.PositiveIntegerField(blank=True, help_text='Enter start year, e.g., 2020', null=True),
        ),
    ]
