# Generated by Django 5.2.5 on 2025-08-27 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_student_academic_year_student_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('internal_assessment_marks', models.JSONField(blank=True, help_text='{subject: marks}', null=True)),
                ('university_exam_marks', models.JSONField(blank=True, help_text='{subject: marks}', null=True)),
                ('cia_test_scores', models.JSONField(blank=True, help_text='{test_type: score}', null=True)),
                ('practice_test_scores', models.JSONField(blank=True, help_text='{test_type: score}', null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('arrear_subjects', models.JSONField(blank=True, help_text='List of arrear subjects (as a list)', null=True)),
                ('marksheet_file', models.FileField(blank=True, null=True, upload_to='marksheets/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='core.student')),
            ],
        ),
    ]
