# Generated by Django 5.2.5 on 2025-08-27 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_academicrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('On Leave', 'On Leave'), ('On Duty', 'On Duty')], max_length=20)),
                ('reason', models.TextField(blank=True, help_text='If absent/on leave/on duty, link to Leave/OD/Bonafide/Gatepass', null=True)),
                ('percentage', models.FloatField(default=0, help_text='Calculated overall attendance percentage')),
                ('bonafide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_bonafides', to='core.bonafide')),
                ('gatepass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_gatepasses', to='core.gatepass')),
                ('leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_leaves', to='core.leave')),
                ('od', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_ods', to='core.od')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student')),
            ],
        ),
    ]
