# Generated by Django 5.2.5 on 2025-08-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonafide',
            name='AHstatus',
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='AHstatus',
        ),
    ]
