# Generated by Django 5.2.5 on 2025-08-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_bonafide_ahstatus_remove_gatepass_ahstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonafide',
            name='ahod_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='ahod_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
