# Generated by Django 5.2.5 on 2025-08-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_bonafide_ahod_reason_gatepass_ahod_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='od',
            name='ahod_hod_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='od',
            name='ahod_hod_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
