# Generated by Django 5.2.5 on 2025-08-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_od_ahod_hod_action_od_ahod_hod_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='ahod_hod_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='ahod_hod_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
