# Generated by Django 5.2.5 on 2025-09-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_leave_ahod_hod_action_leave_ahod_hod_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('001', 'B-Tech Artificial Intelliegnence and Machine Learninig'), ('243', 'B-Tech Artificial Intelliegnence and Data Science')], default='001', max_length=50, null=True)),
                ('semester', models.PositiveIntegerField(choices=[(1, 'SEM - 1'), (2, 'SEM - 2'), (3, 'SEM - 3'), (4, 'SEM - 4'), (5, 'SEM - 5'), (6, 'SEM - 6'), (7, 'SEM - 7'), (8, 'SEM - 8')], default=1, null=True)),
                ('subject1', models.CharField(blank=True, max_length=100, null=True)),
                ('subject2', models.CharField(blank=True, max_length=100, null=True)),
                ('subject3', models.CharField(blank=True, max_length=100, null=True)),
                ('subject4', models.CharField(blank=True, max_length=100, null=True)),
                ('subject5', models.CharField(blank=True, max_length=100, null=True)),
                ('subject6', models.CharField(blank=True, max_length=100, null=True)),
                ('subject7', models.CharField(blank=True, max_length=100, null=True)),
                ('subject8', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['department', 'semester'],
                'unique_together': {('department', 'semester')},
            },
        ),
    ]
