# Generated by Django 5.2.5 on 2025-09-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='core.semester'),
        ),
    ]
