# Generated by Django 5.2.5 on 2025-09-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hods', to='core.department'),
        ),
    ]
