# Generated by Django 5.2.5 on 2025-09-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_hod_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='core.department'),
        ),
    ]
