# Generated by Django 5.2.5 on 2025-09-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_staff_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='departments',
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffsstaff_members', to='core.department'),
        ),
    ]
