# Generated by Django 5.2.5 on 2025-09-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_academicrecord_semester'),
        ('core', '0066_remove_staff_departments_alter_staff_department'),
    ]

    operations = [
    ]
