# Generated by Django 5.2.5 on 2025-09-03 07:13

import django.db.models.deletion
from django.db import migrations, models



def set_ahod_department_null(apps, schema_editor):
    AHOD = apps.get_model('core', 'AHOD')
    AHOD.objects.all().update(department=None)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_staff_departments_alter_staff_department'),
    ]

    operations = [
        migrations.RunPython(set_ahod_department_null),
        migrations.AlterField(
            model_name='ahod',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahod_departments', to='core.department'),
        ),
    ]
