# Generated by Django 5.2.5 on 2025-09-03 07:30

import django.db.models.deletion
from django.db import migrations, models



def set_student_department_null(apps, schema_editor):
    Student = apps.get_model('core', 'Student')
    Student.objects.all().update(department=None)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_ahod_department'),
    ]

    operations = [
        migrations.RunPython(set_student_department_null),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.department'),
        ),
    ]
