# Generated by Django 5.2.5 on 2025-09-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_merge_20250903_1133'),
        ('core', '0068_alter_student_department'),
    ]

    operations = [
    ]
