# Generated by Django 5.2.5 on 2025-09-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_merge_20250903_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_records', to='core.department'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semesters', to='core.department'),
        ),
    ]
