# Generated by Django 5.2.5 on 2025-09-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_academicrecord_department_alter_semester_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='staff1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_subject1_staff', to='core.staff'),
        ),
        migrations.AddField(
            model_name='semester',
            name='staff2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_subject2_staff', to='core.staff'),
        ),
        migrations.AddField(
            model_name='semester',
            name='staff3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_subject3_staff', to='core.staff'),
        ),
        migrations.AddField(
            model_name='semester',
            name='staff4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_subject4_staff', to='core.staff'),
        ),
        migrations.AddField(
            model_name='semester',
            name='staff5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_subject5_staff', to='core.staff'),
        ),
        migrations.AddField(
            model_name='semester',
            name='staff6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_subject6_staff', to='core.staff'),
        ),
        migrations.AddField(
            model_name='semester',
            name='staff7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_subject7_staff', to='core.staff'),
        ),
        migrations.AddField(
            model_name='semester',
            name='staff8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_subject8_staff', to='core.staff'),
        ),
        migrations.DeleteModel(
            name='AcademicRecord',
        ),
    ]
