# Generated by Django 5.2.5 on 2025-09-04 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_semester_staff1_semester_staff2_semester_staff3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='semester',
            name='staff1',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='staff2',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='staff3',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='staff4',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='staff5',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='staff6',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='staff7',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='staff8',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subject5',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subject6',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subject7',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subject8',
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.semester')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_subject_staff', to='core.staff')),
            ],
            options={
                'ordering': ['semester'],
                'unique_together': {('semester', 'name')},
            },
        ),
    ]
