# Generated by Django 5.2.5 on 2025-09-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='elective',
            field=models.ManyToManyField(blank=True, help_text="Select electives relevant to the student's department and semester.", related_name='elective_students', to='core.semestersubject'),
        ),
    ]
