# Generated by Django 5.2.5 on 2025-09-04 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_student_elective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='elective',
        ),
        migrations.AddField(
            model_name='student',
            name='elective',
            field=models.ForeignKey(blank=True, help_text="Select the elective relevant to the student's department and semester.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective_students', to='core.semestersubject'),
        ),
    ]
