# Generated by Django 5.2.5 on 2025-09-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_student_elective_student_elective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='elective',
        ),
        migrations.AddField(
            model_name='student',
            name='elective1',
            field=models.ForeignKey(blank=True, help_text="Select the first elective relevant to the student's department and semester.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective1_students', to='core.semestersubject'),
        ),
        migrations.AddField(
            model_name='student',
            name='elective2',
            field=models.ForeignKey(blank=True, help_text="Select the second elective relevant to the student's department and semester.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective2_students', to='core.semestersubject'),
        ),
        migrations.AddField(
            model_name='student',
            name='elective3',
            field=models.ForeignKey(blank=True, help_text="Select the third elective relevant to the student's department and semester.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective3_students', to='core.semestersubject'),
        ),
    ]
