# Generated by Django 5.2.5 on 2025-09-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_student_elective_student_elective1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestersubject',
            name='is_elective',
            field=models.BooleanField(default=False, help_text='Check if this subject is an elective.'),
        ),
    ]
