# Generated by Django 5.2.5 on 2025-09-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_principal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Principal',
        ),
    ]
