# Generated by Django 5.2.5 on 2025-09-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_passwordotp'),
        ('core', '0079_delete_principal'),
    ]

    operations = [
    ]
