# Generated by Django 5.2.5 on 2025-09-08 15:01

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('core', '0080_merge_0067_passwordotp_0079_delete_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
            ],
            options={
                'verbose_name': 'Principal',
                'verbose_name_plural': 'Principals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='PasswordOTP',
        ),
    ]
