# Generated by Django 5.2.5 on 2025-09-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_principal_delete_passwordotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='od',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
