# Generated by Django 5.2.5 on 2025-09-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_od_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='role',
            field=models.CharField(blank=True, choices=[('mentor', 'Mentor'), ('advisor', 'Advisor'), ('hod', 'HOD'), ('ahod', 'AHOD')], max_length=20, null=True),
        ),
    ]
