# Generated by Django 5.2.5 on 2025-09-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_uploadedresume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedResume',
        ),
    ]
