# Generated by Django 5.2.5 on 2025-09-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_alter_semestersubject_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestersubject',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_subject_staff', to='core.staff'),
        ),
        migrations.DeleteModel(
            name='SemesterSubjectSection',
        ),
    ]
