# Generated by Django 5.2.5 on 2025-09-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_semestersubject_staff_delete_semestersubjectsection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semestersubject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='section',
            field=models.PositiveIntegerField(choices=[(0, 'Artificial Intelliegnence and Machine Learninig'), (1, 'Artificial Intelliegnence and Data Science'), (2, 'A'), (3, 'B'), (4, 'C')], default=2, help_text='Section for which this subject is assigned'),
        ),
        migrations.AlterUniqueTogether(
            name='semestersubject',
            unique_together={('semester', 'name', 'section')},
        ),
    ]
