# Generated by Django 5.2.5 on 2025-09-22 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_alter_semestersubject_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semestersubject',
            unique_together={('semester', 'name')},
        ),
        migrations.RemoveField(
            model_name='semestersubject',
            name='section',
        ),
        migrations.RemoveField(
            model_name='semestersubject',
            name='staff',
        ),
        migrations.CreateModel(
            name='SemesterSubjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.PositiveIntegerField(choices=[(0, 'Artificial Intelliegnence and Machine Learninig'), (1, 'Artificial Intelliegnence and Data Science'), (2, 'A'), (3, 'B'), (4, 'C')])),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_section_staff', to='core.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.semestersubject')),
            ],
            options={
                'ordering': ['subject', 'section'],
                'unique_together': {('subject', 'section')},
            },
        ),
    ]
