# Generated by Django 5.2.5 on 2025-09-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_advisor',
            field=models.BooleanField(default=False, help_text='Indicates if the staff is an advisor.'),
        ),
    ]
