# Generated by Django 5.2.5 on 2025-09-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(choices=[(0, 'Artificial Intelliegnence and Machine Learninig'), (1, 'Artificial Intelliegnence and Data Science'), (2, 'A'), (3, 'B'), (4, 'C')], unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='Select up to 3 sections for this subject.', to='core.section'),
        ),
    ]
