# Generated by Django 5.2.5 on 2025-09-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_section_semestersubject_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestersubject',
            name='sections',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
