# Generated by Django 5.2.5 on 2025-09-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_staff_is_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_advisor',
        ),
    ]
