# Generated by Django 5.2.5 on 2025-09-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '000X_section_and_subject_sections'),
        ('core', '0094_remove_semestersubject_sections_delete_section'),
    ]

    operations = [
    ]
