# Generated by Django 5.2.5 on 2025-09-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_remove_staff_is_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.PositiveIntegerField(choices=[(0, 'Head of the Department'), (1, 'Assistant Head of the Department'), (3, 'Lecturer'), (4, 'Advisor')], default=0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position2',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Head of the Department'), (1, 'Assistant Head of the Department'), (3, 'Lecturer'), (4, 'Advisor')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position3',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Head of the Department'), (1, 'Assistant Head of the Department'), (3, 'Lecturer'), (4, 'Advisor')], default=0, null=True),
        ),
    ]
