# Generated by Django 5.2.5 on 2025-09-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_semestersubject_section_staff_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='bonafide',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='gatepass',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='od',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='percentage',
            field=models.FloatField(default=0, help_text='Calculated subject attendance percentage'),
        ),
    ]
