# Generated by Django 5.2.5 on 2025-09-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_certificateupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateupload',
            name='send_to',
        ),
    ]
