# Generated by Django 5.2.5 on 2025-09-25 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_remove_certificateupload_send_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={},
        ),
        migrations.RemoveField(
            model_name='leave',
            name='AHstatus',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='Astatus',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='Hstatus',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='Mstatus',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='ahod_hod_action',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='ahod_hod_reason',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='created',
        ),
        migrations.CreateModel(
            name='SportsOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_ods', to='core.staff')),
            ],
        ),
        migrations.CreateModel(
            name='SportsODPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('sub', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('start', models.DateTimeField(verbose_name='From-Date')),
                ('end', models.DateTimeField(verbose_name='To-Date')),
                ('proof', models.FileField(blank=True, upload_to='leave/proof')),
                ('certificate', models.FileField(blank=True, upload_to='leave/proof/certificate')),
                ('Astatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('Mstatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('Hstatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('AHstatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('ahod_hod_action', models.CharField(blank=True, max_length=50, null=True)),
                ('ahod_hod_reason', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_sports_od', to='core.staff')),
                ('sports_od', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.sportsod')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
