# Generated by Django 5.2.5 on 2025-09-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_leave_ahstatus_leave_astatus_leave_hstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsodplayer',
            name='sports_od',
        ),
        migrations.RemoveField(
            model_name='sportsodplayer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='sportsodplayer',
            name='hod',
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-id']},
        ),
        migrations.DeleteModel(
            name='SportsOD',
        ),
        migrations.DeleteModel(
            name='SportsODPlayer',
        ),
    ]
