# Generated by Django 5.2.5 on 2025-09-25 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_remove_sportsodplayer_sports_od_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_ods', to='core.staff')),
            ],
        ),
        migrations.CreateModel(
            name='SportsODPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('sports_od', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.sportsod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_od_players', to='core.student')),
            ],
        ),
    ]
