# Generated by Django 5.2.5 on 2025-09-25 04:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_sportsod_sportsodplayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsod',
            options={'ordering': ['-start_date'], 'verbose_name': 'Sports OD', 'verbose_name_plural': 'Sports ODs'},
        ),
        migrations.AlterModelOptions(
            name='sportsodplayer',
            options={'ordering': ['student__department', 'student__roll'], 'verbose_name': 'Sports OD Player', 'verbose_name_plural': 'Sports OD Players'},
        ),
        migrations.RemoveField(
            model_name='sportsod',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='sportsod',
            name='staff',
        ),
        migrations.AlterUniqueTogether(
            name='sportsodplayer',
            unique_together={('sports_od', 'student')},
        ),
        migrations.AddField(
            model_name='sportsod',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='The PET Staff who created this OD.', on_delete=django.db.models.deletion.CASCADE, related_name='sports_ods_created', to='core.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsod',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sportsod',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sportsodplayer',
            name='hod_remark',
            field=models.TextField(blank=True, help_text='Reason for approval/rejection by HOD.', null=True),
        ),
        migrations.AddField(
            model_name='sportsodplayer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sportsod',
            name='event_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sportsodplayer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_od_participations', to='core.student'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.PositiveIntegerField(choices=[(0, 'HOD'), (1, 'Assistant Head of the Department'), (2, 'Professor'), (3, 'Assistant Professor'), (4, 'Associate Professor'), (5, 'PET Staff')], default=0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position2',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'HOD'), (1, 'Assistant Head of the Department'), (2, 'Professor'), (3, 'Assistant Professor'), (4, 'Associate Professor'), (5, 'PET Staff')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position3',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'HOD'), (1, 'Assistant Head of the Department'), (2, 'Professor'), (3, 'Assistant Professor'), (4, 'Associate Professor'), (5, 'PET Staff')], default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='sportsodplayer',
            name='remarks',
        ),
    ]
