# Generated by Django 5.2.5 on 2025-09-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_alter_sportsod_options_alter_sportsodplayer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsod',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
