# Generated by Django 5.2.5 on 2025-09-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_remove_attendance_bonafide_and_more'),
        ('core', '0107_sportsod_body'),
    ]

    operations = [
    ]
