# Generated by Django 5.2.5 on 2025-09-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_sportsod_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scanned Entry Time'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scanned Exit Time'),
        ),
    ]
