# Generated by Django 5.2.5 on 2025-09-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_merge_20250925_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='bonafide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_bonafides', to='core.bonafide'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='gatepass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_gatepasses', to='core.gatepass'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_leaves', to='core.leave'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='od',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_ods', to='core.od'),
        ),
        migrations.AddField(
            model_name='certificateupload',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject for which the certificate is uploaded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_uploads', to='core.semestersubject'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='percentage',
            field=models.FloatField(default=0, help_text='Calculated overall attendance percentage'),
        ),
    ]
