# Generated by Django 5.2.5 on 2025-09-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_attendance_bonafide_attendance_gatepass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateupload',
            name='subject',
            field=models.CharField(blank=True, default=1, help_text='Subject for which the certificate is uploaded', max_length=100),
            preserve_default=False,
        ),
    ]
