# Generated by Django 5.2.5 on 2025-09-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_circular_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='circular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.circular'),
        ),
    ]
