# Generated by Django 5.2.5 on 2025-10-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_gatepass_entry_time_gatepass_exit_time'),
        ('core', '0112_notification_circular'),
    ]

    operations = [
    ]
