# Generated by Django 5.2.5 on 2025-10-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_student_community_student_father_name_student_gender_and_more'),
        ('core', '0113_merge_20251004_2035'),
    ]

    operations = [
    ]
