# Generated by Django 5.2.5 on 2025-11-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_merge_20251020_2134"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="position",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "HOD"),
                    (1, "Assistant Head of the Department"),
                    (2, "Professor"),
                    (3, "Assistant Professor"),
                    (4, "Associate Professor"),
                    (5, "PET Staff"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="position2",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (0, "HOD"),
                    (1, "Assistant Head of the Department"),
                    (2, "Professor"),
                    (3, "Assistant Professor"),
                    (4, "Associate Professor"),
                    (5, "PET Staff"),
                ],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="position3",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (0, "HOD"),
                    (1, "Assistant Head of the Department"),
                    (2, "Professor"),
                    (3, "Assistant Professor"),
                    (4, "Associate Professor"),
                    (5, "PET Staff"),
                ],
                default=0,
                null=True,
            ),
        ),
    ]
