# Generated by Django 5.2.5 on 2025-09-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackaggregate',
            name='aspect_scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackaggregate',
            name='avg_sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='feedbackaggregate',
            name='avg_star_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='feedbackaggregate',
            name='sentiment_distribution',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
