# Generated by Django 5.2.5 on 2025-09-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed360', '0002_feedbackaggregate_aspect_scores_and_more'),
        ('feed360', '000X_add_sentiment_label_to_feedbackresponse'),
    ]

    operations = [
    ]
