# Generated by Django 5.2.5 on 2025-09-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS', '0002_resumeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedresume',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='AI analysis progress (0-100)'),
        ),
    ]
