# Generated by Django 5.2.5 on 2025-09-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATS', '0003_uploadedresume_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedresume',
            name='progress',
        ),
    ]
