# Generated by Django 5.2.5 on 2025-09-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS', '0004_remove_uploadedresume_progress'),
        ('core', '0094_remove_staff_is_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LEAVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='core.student')),
            ],
        ),
    ]
