# Generated by Django 5.2.5 on 2025-09-02 15:25

import resumebuilder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='declaration_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='declaration_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to=resumebuilder.models.resume_image_upload_path),
        ),
    ]
