# Generated by Django 5.2.5 on 2025-09-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0002_resume_declaration_content_resume_declaration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='declaration_content',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='declaration_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='declaration_place',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='signature_image',
        ),
    ]
