# Generated by Django 5.2.5 on 2025-09-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0003_remove_resume_declaration_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='declaration_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='declaration_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='declaration_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
