# Generated by Django 5.2.5 on 2025-09-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0004_resume_declaration_date_resume_declaration_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='declaration_place',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='declaration_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='declaration_text',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
