# Generated by Django 5.2.5 on 2025-09-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0005_alter_resume_declaration_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='declaration_signature',
            field=models.ImageField(blank=True, null=True, upload_to='resume/signatures/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='declaration_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
