# Generated by Django 5.2.5 on 2025-09-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0006_alter_resume_declaration_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='declaration_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
