# Generated by Django 5.2.5 on 2025-09-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0008_resume_email_resume_name_resume_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
